apiVersion: v1
kind: Service
metadata:
  name: sampleapplication
  namespace: namespace-workflow-1686115602577
spec:
  type: LoadBalancer
  selector:
    app: sampleapplication
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080